on: 
  workflow_call:
    inputs:
      qt-version:
        description: Qt version to use
        type: string
      artifact:
        description: Artifact name to upload to
        type: string
        default: ''
      build-type:
        description: CMake build type
        type: string
        default: Release
      runs-on:
        description: Type of machine to run the job on
        type: string
        default: ubuntu-latest

jobs:
  build:
    name: Build qShogi
    runs-on: ${{ inputs.runs-on }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt ${{ inputs.qt-version }}
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ inputs.qt-version }}

      - name: Build qShogi (${{ inputs.build-type }})
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} ..
          make

      - name: Upload artifact
        if: ${{ inputs.artifact != '' }}
        uses: actions/upload-artifact@v2
        with: 
          name: ${{ inputs.artifact }}
          path: build/src/qShogi/qShogi
